name: Deploy to GoDaddy via FTP

on:
  workflow_dispatch:  # Allow manual trigger from GitHub Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GoDaddy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}  # FTP server (e.g., ftp.qrcodegens.com)
          username: ${{ secrets.FTP_USERNAME }}  # FTP username
          password: ${{ secrets.FTP_PASSWORD }}  # FTP password
          port: 21  # FTP port
          local-dir: ./  # Local directory to deploy
          server-dir: /public_html/  # Remote server directory
