name: Deploy to GoDaddy via FTP

on:
  workflow_dispatch:  # Allow manual trigger from GitHub Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GoDaddy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Change to your build folder
          server-dir: /home/m7ryb96exju0/  # Change to your folder on GoDaddy if needed
          protocol: ftps
