name: Deploy to GoDaddy via FTP

on:
  workflow_dispatch:  # Allow manual trigger from GitHub Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GoDaddy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}  # GoDaddy FTP server address
          ftp-username: ${{ secrets.FTP_USERNAME }}  # Your FTP username
          ftp-password: ${{ secrets.FTP_PASSWORD }}  # Your FTP password
          local-dir: ./  # Path to your local folder to deploy (adjust as needed)
          remote-dir: /home/m7ryb96exju0/  # Path to your GoDaddy folder
          ftp-port: 21  # Explicit FTPS or FTP port (use 21 for FTP)
          protocol: ftp  # Set to 'ftps' if using FTPS
