name: Deploy to GoDaddy via SFTP

on:
  workflow_dispatch:  # Allow manual trigger from GitHub Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GoDaddy via SFTP
        uses: appleboy/ftp-action@v1.2.0
        with:
          host: ${{ secrets.FTP_SERVER }}  # FTP server (e.g., ftp.qrcodegens.com)
          username: ${{ secrets.FTP_USERNAME }}  # FTP username
          password: ${{ secrets.FTP_PASSWORD }}  # FTP password
          port: 22  # SFTP port
          protocol: sftp  # Use SFTP instead of FTP
          local-dir: ./  # Local directory to deploy
          server-dir: /public_html/  # Remote server directory
